### ISSUE TITLE
Bug: Error sending question to the server

### ISSUE THREAD

**Issue by zameel7** [abconlinecourses/chatgpt-xblock#4]
- I have installed the xblock to our instance and enabled it in the advanced block 
- Added the xblock into a unit in a course and added required details to it

Tried to submit a question and get an answer but the console shows this
![Screenshot 2023-05-19 at 11 09 30 AM](https://github.com/abconlinecourses/chatgpt-xblock/assets/43750093/595cba03-0118-440d-a6c1-0b1549e88291)

Did anyone face the same? Is it that I missed to add something in the installed apps?

**Comment by zameel7** [comment]
I have added "chatgptxblock" into lms-env inside ADDL_INSTALLED_APPS. Isn't that where it should be added?

**Comment by isankadn** [comment]
> 

@zameel7 What's your Open edX version? And especially the Python version? Could you let me know if you checked the error logs?

**Comment by zameel7** [comment]
@isankadn , we are using tutor==15.3.5 (Open edX Olive) and Python version is 3.11

**Comment by isankadn** [comment]
@zameel7 then it should work, we have tested it on tutor==15.3.5. How did you install it? using a tutor plugin?

**Comment by zameel7** [comment]
@isankadn 


- Added the ChatGPT XBlock repository to the ```private.txt``` in ```$(tutor config printroot)/env/build/openedx/requirements``` as:     ```git+https://github.com/abconlinecourses/chatgpt-xblock.git```
- Rebuild the Open Edx image
- Created a plugin inside 
    ```yml
    name: chatgpt
    version: 0.0.1
    patches:
      lms-env: |
        ADDL_INSTALLED_APP:
          - "chatgptxblock"
    ```
- Enabled the newly created plugin as: ```tutor plugins enable chatgpt```
- Saved the config and relaunched
    ```
    tutor config save
    tutor k8s launch
    ```

**Comment by zameel7** [comment]
> > 
> 
> @zameel7 What's your Open edX version? And especially the Python version? Could you let me know if you checked the error logs?

Currently when I checked the logs, I got to find this that maybe causing the issue:

```
openai.error.RateLimitError: You exceeded your current quota, please check your plan and billing details.
tutor_local-lms-1  | [pid: 7|app: 0|req: 43/159] 172.18.0.10 () {54 vars in 3554 bytes} [Mon May 22 11:37:22 2023] POST /courses/course-v1:edX+DemoX+Demo_Course/xblock/block-v1:edX+DemoX+Demo_Course+type@chatgptxblock+block@49099150a68349398c17aeec21c96292/handler/get_answer => generated 9912 bytes in 814 msecs (HTTP/1.1 500) 9 headers in 582 bytes (1 switches on core 0)
```

**Comment by zameel7** [comment]
I had been changing the API keys to check if its working and after 2 tries, a new API got it to work

**Comment by isankadn** [comment]
@zameel7 I see, Thanks for sharing. It seems API key issue.
